### ISSUE TITLE
Errors in plugin example?

### ISSUE THREAD

**Issue by lklein** [fusionjs/fusionjs.github.io#118]
I am reading the "creating a Fusion.js plugin" [page ](https://github.com/fusionjs/fusionjs.github.io/blob/af391661914b9294ccd51e120634cb5c2e56d922/documentation/docs/guides/creating-a-plugin/index.md)but am a little confused, esp. about the following code:

```
// src/plugins/foo.js
import {createToken} from 'fusion-core';
import {ExampleToken} from '';

export const ExampleToken = createToken('ExampleToken');

export default createPlugin({
  deps: {example: ExampleToken},
  provides({example}) {
    example.sayHello();
  },
});
```

My problems are: 

- ExampleToken is imported from ''.  Is this valid?
- Another const ExampleToken is created and exported.  Wouldn't it collide with the token already created in src/plugins/example.js, assuming createToken creates the same token given the same input?

I think the correct code would be 

```
// src/plugins/foo.js
import {createToken} from 'fusion-core';
import {ExampleToken} from './example';

export const FooToken = createToken('FooToken');

export default createPlugin({
  deps: {example: ExampleToken},
  provides({example}) {
    example.sayHello();
  },
});
```

Please let me know.  I'd be happy to submit a PR.

**Comment by micburks** [comment]
Thanks for the issue!
