### ISSUE TITLE
Assorted typos in contributing instructions and documentation

### ISSUE THREAD

**Issue by austin94** [fusionjs/fusionjs.github.io#18]
👋 Hi everyone. While going through the getting-started guide and the API documentation I found some assorted typos.

@KevinGrandon @AlexMSmithCA @nadiia it was great to meet you all at the meetup yesterday!

#### README.md

> yarn ~~boostrap~~ **bootstrap**

#### content/tokens.md

> You have a Fusion.js application ~~with~~ with many dependencies.

#### documentation/docs/getting-started/why-fusion.md

> Our vendor JavaScript ~~bundle small~~ **bundle is small** through usage...

> The core technologies recommended in these ~~guids~~ **guides**, such as React and Redux

## Unrelated

Fusion is looking really good! Do you have any more repos with some more fleshed-out examples?

**Comment by AlexMSmithCA** [comment]
Hey @austin94!  Appreciate the PR here as we approach a broader release.  We are looking to make some fully featured external examples prior to the release, so stay tuned!  To date, I don't believe we have any open sourced yet.  (Correct me if wrong, @nadiia  / @KevinGrandon)

**Comment by KevinGrandon** [comment]
This is great, thank you for your contribution!

> Fusion is looking really good! Do you have any more repos with some more fleshed-out examples?

I have this mentioned in the docs and am looking at integrating these in a more "official" way, https://github.com/KevinGrandon/fusion-boilerplate

Also looking at adding a more fleshed out example app, TODO or hackernews for example. I would also be happy to collaborate with you on one of these if you want to give it a shot.

**Comment by austin94** [comment]
I would definitely be interested in doing a larger example.

Is this something you would want in your boilerplate repo? If so, I can create another issue to plan/discuss more.
