### ISSUE TITLE
Add Reframe to Framework Comparison

### ISSUE THREAD

**Issue by brillout** [fusionjs/fusionjs.github.io#75]
Would you guys be up for that? I'd create a PR and try to be unbiased.

Reframe (https://github.com/reframejs/reframe) is similar in that it focuses on modularity (it is also based on plugins that use integration points and DI) but is different in that it focuses on flexibility (it's progressively ejectable.)

**Comment by KevinGrandon** [comment]
Thank you for the suggestion. At this time we are only adding additional framework comparisons for frameworks from which we get a large number of questions about. Once we notice a lot of questions coming in, or comparisons, we will gladly add Reframe here. In the meantime, feel free to update your issue, or respond here with a comparison in case people find this in the future.

Closing for now, but will revisit should we receive a lot of questions about reframe, or using reframe and Fusion.js.
